version: '3'
services:
  typesense-server:
    image: typesense/typesense:27.1
    restart: on-failure
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=$TYPESENSE_APIKEY --enable-cors'
  webapp:
    build: .
    restart: on-failure
    volumes:
      - ./public/rfcs:/app/public/rfcs
    ports:
      - 3000:3000
